# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Askcloud < Formula
  desc ""
  homepage "https://github.com/chinmaysomani07/askcloud"
  version "0.1.0"

  on_macos do
    url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.1.0/askcloud_0.1.0_darwin_all.tar.gz"
    sha256 "2086a9b94087e18555f0565de09dd66af05f20e2c00156ea99e27bf7260439f2"

    def install
      bin.install "askcloud"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.1.0/askcloud_0.1.0_linux_arm64.tar.gz"
      sha256 "99f48485b148f012f596697e17d6c058611f989f6bbc00a775bcb6b0f7ec04ea"

      def install
        bin.install "askcloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.1.0/askcloud_0.1.0_linux_amd64.tar.gz"
      sha256 "50cc0359b8b23fa526e141f2898aad439d002cc4915a0e0f3176e9c7bd50e154"

      def install
        bin.install "askcloud"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.1.0/askcloud_0.1.0_linux_armv6.tar.gz"
      sha256 "8d517f914462f89200fce236d4f46ab8cb216861e6df143047dfc4432ff0631b"

      def install
        bin.install "askcloud"
      end
    end
  end
end
