# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Askcl < Formula
  desc ""
  homepage "https://github.com/chinmaysomani07/askcloud"
  version "0.0.6"

  on_macos do
    url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.6/askcloud_0.0.6_darwin_all.tar.gz"
    sha256 "77c6b0f85c77da5b43d5952d6632b03cfe293df895e4b4e06d84d35d6cbc5579"

    def install
      bin.install "askcloud"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.6/askcloud_0.0.6_linux_armv6.tar.gz"
      sha256 "2ac4d790123ac191ba3252fa952c7f3e1bcd8d4fabcab4e5237b984a080f6aec"

      def install
        bin.install "askcl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.6/askcloud_0.0.6_linux_arm64.tar.gz"
      sha256 "2b2d36f394098bee4b8701da88b7a21a7928299ec7f5ea85dea374858ac150aa"

      def install
        bin.install "askcl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.6/askcloud_0.0.6_linux_amd64.tar.gz"
      sha256 "a81e7474981cad0256017de309090df7590e63e7c05398c2310d607a3a7cb09f"

      def install
        bin.install "askcl"
      end
    end
  end
end
