# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudLens < Formula
  desc ""
  homepage "https://github.com/chinmaysomani07/askcloud"
  version "0.0.5"

  on_macos do
    url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.5/askcloud_0.0.5_darwin_all.tar.gz"
    sha256 "1d1f85e65392ca8e30991733dc35e2f411548440adbda3548c68057fe941b356"

    def install
      bin.install "askcloud"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.5/askcloud_0.0.5_linux_arm64.tar.gz"
      sha256 "b8c329ce87b8999719c7535dc6e5aac42b6a67aae268cd49a0edc13dd8ace99c"

      def install
        bin.install "askcl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.5/askcloud_0.0.5_linux_amd64.tar.gz"
      sha256 "cebf3cefaea97f4cb3808bbf95a15c50b093b0daa653077d0fe9b7164655a8e4"

      def install
        bin.install "askcl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.5/askcloud_0.0.5_linux_armv6.tar.gz"
      sha256 "7f99a7f6574b7b35cd06d427bac3c77806a9f057fe64cd6b650f5f1068fa6e47"

      def install
        bin.install "askcl"
      end
    end
  end
end
