# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudLens < Formula
  desc ""
  homepage "https://github.com/chinmaysomani07/askcloud"
  version "0.9"

  on_macos do
    url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.9/askcloud_0.9_darwin_all.tar.gz"
    sha256 "8bf8f904e86e7006ef9bf4cf179d57728be0bf587f587d960335c43b19bd3db9"

    def install
      bin.install "askcloud"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.9/askcloud_0.9_linux_arm64.tar.gz"
      sha256 "13661d93b039cc92a9b87a1020bc5c4e723e2df85400923358815fdcc29d80e0"

      def install
        bin.install "askcloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.9/askcloud_0.9_linux_amd64.tar.gz"
      sha256 "3bd608e33aa0f506a8cb6beae61d327a89e9927787be9c082fd092e602fdaef0"

      def install
        bin.install "askcloud"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.9/askcloud_0.9_linux_armv6.tar.gz"
      sha256 "4ed4645595bcb51fd7b8e7684f7176c16aa9fad5cb9d7bf7ce5a93a74738d26f"

      def install
        bin.install "askcloud"
      end
    end
  end
end
