# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tempaskcl < Formula
  desc ""
  homepage "https://github.com/chinmaysomani07/askcloud"
  version "0.0.9"

  on_macos do
    url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.9/askcloud_0.0.9_darwin_all.tar.gz"
    sha256 "ff4e057fc2874916f5040213f33d7f5a6eccdb8295934c363ff76b4efc2416b1"

    def install
      bin.install "askcloud"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.9/askcloud_0.0.9_linux_arm64.tar.gz"
      sha256 "456e9178807cda656e830d32a28b2421e58946110a5757dab203ab286c8cfe8b"

      def install
        bin.install "askcloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.9/askcloud_0.0.9_linux_amd64.tar.gz"
      sha256 "429bc1b803c6250a36e8040434c7e58b118147499a9f8e7f098c909349f60c4b"

      def install
        bin.install "askcloud"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.9/askcloud_0.0.9_linux_armv6.tar.gz"
      sha256 "c5c2f6d63e8e63de1247ef11a6755b118b82f6b241104cbcf3472a44da482f3b"

      def install
        bin.install "askcloud"
      end
    end
  end
end
