# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tempask12 < Formula
  desc ""
  homepage "https://github.com/chinmaysomani07/askcloud"
  version "0.0.12"

  on_macos do
    url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.12/askcloud_0.0.12_darwin_all.tar.gz"
    sha256 "eab4775f73c947c0543da8b5a6a6bc2a694c1d1dd52e50dd541e74b78260daf2"

    def install
      bin.install "askcloud"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.12/askcloud_0.0.12_linux_arm64.tar.gz"
      sha256 "38916621ac820910d2987fa687c66707718dcc92829e13d995f921c6728c0497"

      def install
        bin.install "askcloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.12/askcloud_0.0.12_linux_amd64.tar.gz"
      sha256 "b62bf9eec54d939345234a587af9a002f6b9ad36a158dbfce4ed211b3f950c4b"

      def install
        bin.install "askcloud"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.12/askcloud_0.0.12_linux_armv6.tar.gz"
      sha256 "67fc37b8914ca97d7687f204f1fe06887742440f659055d74cc296bdb53b5399"

      def install
        bin.install "askcloud"
      end
    end
  end
end
