# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tempask13 < Formula
  desc ""
  homepage "https://github.com/chinmaysomani07/askcloud"
  version "0.0.13"

  on_macos do
    url "https://github.com/chinmaysomani07/askcloudtemp/releases/download/v0.0.13/askcloudtemp_0.0.13_darwin_all.tar.gz"
    sha256 "8e649ef05d2cc4b8fa572347a931cc43db6a0ab6be48f9b76f34d6b49135e8d2"

    def install
      bin.install "askcloudtemp"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloudtemp/releases/download/v0.0.13/askcloudtemp_0.0.13_linux_armv6.tar.gz"
      sha256 "7e686bf3f700e535af0634b302b0917407b3cd8daa080ec5dc304bfd1a21fd18"

      def install
        bin.install "askcloudtemp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chinmaysomani07/askcloudtemp/releases/download/v0.0.13/askcloudtemp_0.0.13_linux_amd64.tar.gz"
      sha256 "c45780d241feaf7bb4b9a5aacb22e585fb984e123b16264b9ac7b8732b5a7009"

      def install
        bin.install "askcloudtemp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloudtemp/releases/download/v0.0.13/askcloudtemp_0.0.13_linux_arm64.tar.gz"
      sha256 "4b264b8df82875a0eb69f3b9bc014aafa43daa5871c23d83ac80637045d91764"

      def install
        bin.install "askcloudtemp"
      end
    end
  end
end
