# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tempask11 < Formula
  desc ""
  homepage "https://github.com/chinmaysomani07/askcloud"
  version "0.0.11"

  on_macos do
    url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.11/askcloud_0.0.11_darwin_all.tar.gz"
    sha256 "c932db21e32b51666f321b6edc92a35f942920c8844dcc4d51c09709a018dc96"

    def install
      bin.install "askcloud"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.11/askcloud_0.0.11_linux_armv6.tar.gz"
      sha256 "f07b5320607e2b882237d2b68f1ee5713a2a98ee0eae545509105d2bf4411456"

      def install
        bin.install "askcloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.11/askcloud_0.0.11_linux_amd64.tar.gz"
      sha256 "e0b8c7a36489f620e71de06599e5200ce9438a07b8c8779a536a675cbfcfad8e"

      def install
        bin.install "askcloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.11/askcloud_0.0.11_linux_arm64.tar.gz"
      sha256 "d1c884a77b66b837eb5173943136882a1b44a51e070fa23b4e2010db6aa9c3d8"

      def install
        bin.install "askcloud"
      end
    end
  end
end
