# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tempaskcll < Formula
  desc ""
  homepage "https://github.com/chinmaysomani07/askcloud"
  version "0.0.10"

  on_macos do
    url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.10/askcloud_0.0.10_darwin_all.tar.gz"
    sha256 "455be46637f9acdc166103c1b4417d4c4267ca9f88bcbbcbbd60099f6c39f8b5"

    def install
      bin.install "askcloud"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.10/askcloud_0.0.10_linux_armv6.tar.gz"
      sha256 "229b56db1e21256e35f8f53acfba2af6e789a4c57c7878765576d5d4f3f5558c"

      def install
        bin.install "askcloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.10/askcloud_0.0.10_linux_arm64.tar.gz"
      sha256 "f04458378fbd561bae0e548d7262bfcae00ce41883e52f88ce6fda72fcc1a49c"

      def install
        bin.install "askcloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chinmaysomani07/askcloud/releases/download/v0.0.10/askcloud_0.0.10_linux_amd64.tar.gz"
      sha256 "67a7b9af60ff90b1ca81ef221116c022f196e796f2b3f482059157b6682475f5"

      def install
        bin.install "askcloud"
      end
    end
  end
end
